### ISSUE TITLE
Oops

### ISSUE THREAD

**Issue by bovarysme** [JoshuaDoes/adpcm-go#1]
Hi,

I didn't consider this library could have users when I deleted it, I'm sorry for the trouble caused!
Feel free to take ownership and/or change the license to something that's more convenient for you.

**Comment by JoshuaDoes** [comment]
It's okay! I'm glad it existed but I'm gonna leave everything as-is, minus the fixes I made to the tables (because we all had it wrong from the start apparently).

Thank you for making a simple and great package, it's been really helpful and I'm hoping others can find a use out of it like me. I'm gonna leave this issue open for a little while so others can see it c:

**Comment by bovarysme** [comment]
No worries! I'm glad it's been helpful to you. :bowing_woman:

Right, the original step table is used in some Japanese rhythm games and is definitely non-standard. I believe the one you got is what most programs use (including ffmpeg...)

**Comment by JoshuaDoes** [comment]
It was pulled straight out of both ffmpeg and Flipnote Studio by @jaames and @khang06 iirc, so I made sure to update it accordingly. I'm actually considering updating the repo slightly to preserve both step tables, with a user choice to optionally switch into the non-standard variant (as it still has its use cases here and there).
